config/routes.rb
Rails.application.routes.draw do
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/', to: 'application#welcome' 
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  # review nested routes --> add nested routes
  # nested index, nested show, nested new

  resources :users, only: [:new, :show, :create, :edit, :update, :destroy]
   # be curious about this resource
  resources :reviews do 
    resources :comments, only: [:new, :create, :show, :index]
    # get 'reviews/:id/comments' to: 'comments#index'
    # get 'reviews/new' to: 'reviews#new'
  end

  delete '/logout', to: 'sessions#destroy'
  root 'application#welcome' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user 
    belongs_to :review
    scope :most_recent, -> {Comment.order("created_at DESC")}
    # review scopes


    def self.deleted_user
        Comment.all.each do |comment|
            if comment.user == nil
                comment.destroy 
            end
        end 
    end 


    def normalize_date
        self.created_at = created_at.strftime("%B %-d, %Y %-l:%M %p")
    end 

end

app/models/review.rb
class Review < ApplicationRecord
    validates :title, :description, :rating, :reviews, presence: true 
    belongs_to :user
    has_many :comments
    has_many :users, through: :comments 
    scope :alpha, -> { order(:title) }
    scope :find_by_title, -> (title) { where("title LIKE ?", title) } #name something else for portfolio

    
  
    def self.deleted_user
        Review.all.each do |reviews|
            if reviews.user == nil 
                reviews.destroy
            end
        end
    end
  
  
    def self.ranked_reviews 
        reviews = Review.order("reviews DESC")
        return reviews 
    end

    def self.search(search)
        if search
            review = Review.find_by(title: search)
            if review
                self.where(review_id: review)
            else
                Review.all
            end
        else
            Review.all
        end
    end
  
  end

app/models/user.rb
class User < ApplicationRecord

    has_many :reviews  
    has_many :comments
    has_many :commented_reviews, through: :comments, source: :review 

    has_secure_password 

    validates :username, presence: true 
    validates :username, uniqueness: {message: "Username already in use, please try again." }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?, :validate, :owned_by_user?, :email_clear, :current_review

  
  def current_user
      @current_user ||= User.find_by_id(session[:user_id])
  end

  def logged_in?
      !!current_user
  end


  def validate 
      unless @user.id == current_user.id 
          flash[:error] = "Restricted area."
          redirect_to reviews_path
      end
  end 

  def owned_by_user?(reviews) 
      if @review != nil 
          if current_user.id == @review.user_id
              return true 
          else 
              false 
          end
      end
  end


  def email_clear(email)
      username = email.split(/@gmail.com/)
      username[0]
  end

  def current_review
      @review = Review.find_by_id(params[:id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :logged_in?

  def new
      @comment = Comment.new 
      @review = Review.find_by_id(params[:review_id])
  end

  def create 
      @comment = Comment.new(content: params[:comment][:content], user_id: current_user.id, review_id: params[:review_id])
      if @comment.save
          redirect_to review_comments_path(@comment.review_id)
      end 
  end

  def show 
      @comment = Comment.find_by_id(params[:review_id][:comment])
  end


  def index
      if params[:review_id] && review = Review.find_by(id: params[:review_id]) 
          @comments = review.comments.most_recent 
      else
          @comments = Comment.all
      end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :logged_in? 
  before_action :current_review, only: [:show, :edit, :update, :destroy] 

  def index
    if params[:title]
        @reviews = Review.find_by_title(params[:title])
    else
        @reviews = Review.order(sort_column + " ")
    end
  end

  def new
      @review = Review.new 
  end

  def create
      @review = Review.new(review_params)
      @review.user_id = session[:user_id]
      if @review.valid?
          @review.save 
          redirect_to review_path(@review)
      else 
          redirect_to new_review_path 
      end
  end

  def show
  end

  def edit
      unless @review.user_id == current_user.id
          flash[:error] = "You cannot edit or delete this because you did not create it!"
          redirect_to reviews_path
      end
  end

    def update
        if @review.update(review_params)
            redirect_to review_path(@review)
        else 
            redirect_to edit_review_path 
        end
    end

    def destroy
        if current_user 
            @review.destroy 
            redirect_to reviews_path
        end
    end

    # def search
    #     @reviews = Review.search(params[:search])
    #     redirect_to search_review_path
    # end

  private

  def sort_column
    Review.order(:title).include?(params[:sort]) ? params[:sort] : "title"
  end

  def review_params
      params.require(:review).permit(:title, :description, :rating, :reviews, :search)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def login
  end

  def create
    @user = User.find_by(username: params[:user][:username])

    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id 
      redirect_to reviews_path 
    else 
      flash[:error] = "User not found. Please login with the correct credentials."
      redirect_to login_path 
    end
  end

  def destroy 
    session.delete :user_id 
    redirect_to root_path 
  end

  def omniauth
    @user = User.find_or_create_by(uid: auth[:uid]) do |u|
      u.username = email_clear(auth[:info][:email])
      u.password = SecureRandom.hex
    end
    session[:user_id] = @user.id
    redirect_to reviews_path   
  end

  private
      
  def auth 
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_user, only: [:show, :edit, :update, :destroy]

  
  def new
    @user = User.new
  end

  def create 
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id 
      redirect_to reviews_path(@user)
    else 
      redirect_to new_user_path
      flash[:error] = "Username is not available, please use a unique username."
      # visit error message display & requirements
    end
  end
  
  def show
    validate
  end
  
  def edit
    validate 
  end

  def update
    if @user.valid?
      @user.update(username: params[:user][:username])
      redirect_to user_path(@user)
    else 
      redirect_to edit_user_path 
    end
  end

  def destroy 
    @user.destroy 
    redirect_to root_path 
    flash[:error] = "Account deleted."
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

  def find_user 
    @user = User.find_by_id(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/readers_helper.rb
module ReadersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/home.html.erb
<html>
<head>
</head>
<div id= "home">
    <div>
       <h5 id="welcome_to">Welcome to</h5>
            <h1 id= "bookhub"> bookHub </h1>
            <br>
        </div>
    <div>
        <h3 id="instructions">Sign up or login.</h3>
        <br>
        <div id="button">
            <h5><%= flash[:error] %></h5>
            <a id="signup" href="/signup"><button>Join the Hub</button></a>
            <a id="login" href="/login"><button>Log In</button></a>
            <h5><%= button_to "Log in with Google", '/auth/google_oauth2', method: :get %></h5>
            <h5> © 2020 bookHub <h5>
        </div>
    </div>
</div> 

app/views/application/welcome.html.erb
<html>
<head>
</head>
<div id= "welcome">
    <div>
       <h5 id="welcome_to">Welcome to</h5>
            <h1 id= "bookhub"> bookHub </h1>
            <br>
        </div>
    <div>
        <h3 id="instructions">Sign up or login!</h3>
        <br>
        <div id="button">
            <h5><%= flash[:error] %></h5>
            <a id="signup" href="/signup"><button>Create An Account</button></a>
            <a id="login" href="/login"><button>Log In</button></a>
            <h5><%= button_to('Log in with Google!', '/auth/google_oauth2', method: :get) %></h5>
            <h5> © 2020 bookHub <h5>
        </div>
    </div>
</div> 

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/comments/index.html.erb
<% Comment.deleted_user %>
<% unless @comments.count == 0 %>
    <fieldset> 
        <legend><h4>Comments Thread:</h4></legend>
            <% @comments.each do |comment| %>
                <br>
                    <ul>
                        <li><p><%= comment.content %> by <%= comment.user.username %> - <%= comment.normalize_date %></p></li>
                    </ul>
            <% end %>
    <% end %>
</fieldset>



<% if logged_in? %>
    <br>
    <%= button_to 'Add Comment', new_review_comment_path, method: :get %>
    <br>
    <%= button_to 'Return to Home', reviews_path, method: :get %>
    <br> 
<% else %>
    <%= button_to 'Return', "/", method: :get %>
    <br>
<% end %>

app/views/comments/new.html.erb
<h3><%= @review.title%></h3>

<%= form_for [@review, @comment] do |f| %>
    <%= f.label 'Leave a comment' %>
    <br>
    <%= f.text_area :content %>
    <br>
    <br>
    <%= f.submit "Post Comment" %>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(object.errors.count, "error") %> stopped this from being saved:</h3>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><i><%= msg %></i></li>
    <% end %>
    </br>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
<div id= "welcome">
    <div>
        <h1 id= "bookhub"> bookHub </h1>
         <br>
    </div>
<div>
  <nav>
  
    <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
        <li><%=  link_to  "New Review", new_review_path, method: :get %></li>
        <li><%= link_to 'Your Profile', user_path(current_user), method: :get %></li>
        <li><%= link_to 'Logout', logout_path, method: :delete %></li>
      <% end %>
    </ul>
  </nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>bookHub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= render partial:'layouts/errors', locals: {object: @review} %>

<h5><%= flash[:error] %></h5>
<%= form_for @review do |f| %>
    <%= f.label 'What is the title of the book you read?' %>
    <%= f.text_field :title %>
    <br>
    <br>
    <%= f.label 'Please provide a description of the book you read.' %>
    <%= f.text_area :description %>
    <br>
    <br>
    <%= f.label 'What would you rate the book?' %>
    <%= f.text_field :rating %>
    <br>
    <br>
    <%= f.label 'What is your review?' %>
    <%= f.text_area :reviews %>
    <br>
        <br>
    <%= f.submit "Submit Book" %>
<% end %>

app/views/reviews/edit.html.erb
<h3> Edit Your Book Review</h3>

<%= render partial: 'form'%>

app/views/reviews/index.html.erb
<%= render 'layouts/footer' %>

<h3> Welcome <%= current_user.username %>! These are your reviews so far:</h3>
<h5><%= flash[:error] %></h5>
<br>
<% if current_user.reviews.count == 0 %>
    <h4> You have not written any reviews yet </h4>
<br>
<% else %>
<% current_user.reviews.each do |review| %>
    <ul>
        <h3><%= link_to "#{review.title}", review_path(review) %></h3>
    </ul>
    <% end %>
<% end %>
<br> 
<br>
    <br>
<h3 style="color:black;"> || Other Readers' book reviews! ||</h3>
<br>
<br>
    <br>

<%= form_tag reviews_path, :method => :get do %>
  <%= label_tag "Search for a Book Review:" %>
  <%= text_field_tag :title, params[:title] %>

  <%= submit_tag "Search", :title => nil %>
<% end %>

<% Review.deleted_user %> 
<% @reviews.each do |review| %>
      <tr>
      <% if review.user_id != current_user.id  %>
      <h3><%= link_to review.title, review_path(review) %> - <%= review.rating %> Rating</h3>
      </tr>


        <% end %>
    <% end %>
<br>
<br>


<h3> © 2020 bookHub <h3>

app/views/reviews/new.html.erb
<h3>Create a Book Review</h3>

<%= render partial: 'form'%>

app/views/reviews/search.html.erb
<%# <h1>Search by Title</h2> %>

<%# <%= form_tag(reviews_path, method: :get) do %> 
  <%# <%= text_field_tag(:search, params[:search]) %> 
  <%# <%= submit_tag ("Search") %> 
<%# <% end %> 

<%# <% @reviews.each do %>
  <%# <ul> %>
    <%# <li> <%= link_to review.title, review_path(review) </li><br>
  <%# </ul> %>
<%# <% end %>

app/views/reviews/show.html.erb
    <h1><%= @review.title %></h1>
    <h2>Description: <%= @review.description%></h2>
    <h2>Review: <%= @review.reviews%> </h2>
    <h3>Rating: <%= @review.rating %></h3>
    <br>
    <p>Post created by: <h3><%= @review.user.username %></h3></p>
    <h5><%= flash[:error] %></h5>
    
<br>
<% if logged_in? %>
    <br>
    <%= button_to 'Add Comment', new_review_comment_path(@review), method: :get %>
    <br>
    <%= button_to 'Comments Thread', review_comments_path(@review), method: :get %>
    <br>
    <% if owned_by_user?(@review)%>
        <%= button_to 'Delete book review', review_path(@review), method: :delete %>
        <br>
        <%= button_to 'Edit book review', edit_review_path(@review), method: :get %>
    <% end %>
    <br>
    <%= button_to 'Return to Home', reviews_path, method: :get %>
    <br> 
<% else %>
    <%= button_to 'Return', "/", method: :get %>
    <br>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f|%>
<p>
  <%= f.label :username %>
  <%= f.text_field :username %>
</p>
<p>
  <%= f.label :password %>
  <%= f.password_field :password %>
</p>
  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<%= render partial:'layouts/errors', locals: {object: @user} %>

<h5><%= flash[:error] %></h5>
    <h2>Edit or Delete your account</h2>
    <%= form_for @user do |f| %>
        <%= f.label :username %>
        <%= f.text_field :username %>
        <%= f.submit "Edit User Name" %>
    <% end %>
    <br>
    <%= button_to 'Deactivate Account', user_path, method: :delete %>
    <br>
    <%= button_to 'Return to Profile', user_path, method: :get %>

app/views/users/new.html.erb
<h1> Sign up </h1>
<h5><%= flash[:error] %></h5>

<%= form_for @user do |f| %>
    <br>
    <%= f.label 'Username' %>
    <br>
    <%= f.text_field :username %>
    <br>
    <%= f.label 'password' %>
    <br>
    <%= f.password_field :password %>
    <br>
    <br>
    <%= f.submit "Create Account" %>
<% end %>
<br>
<%= button_to "Log In", "/login", method: :get %>

app/views/users/show.html.erb
<h3>Welcome back, <%= current_user.username %>! </h3>



<% if current_user.reviews.count == 0 %>
    <h4> You need to add some review Reviews! </h4>
<% end %>
<h2> Here are your reviews by rating, in descending order so far: </h2>
    <% Review.ranked_reviews.each do |b| %>
        <% if b.user_id == current_user.id  %>
            <ul>
                <h3><%= link_to b.title, review_path(b) %> - <%= b.rating %> Rating </h3>
            </ul>
        <% end %>
    <% end %>

<%= button_to "Add a new book review", new_review_path, method: :get %> 
<br>
<br>
<%= button_to "See other Readers' Reviews", review_path, method: :get %>
<br>
<br>
<%= button_to "Account Settings", edit_user_path, method: :get %>
<br>
<br>
<%= button_to "Log Out", logout_path, method: 'delete' %>